name: Document Export

on: [push]

jobs:
  Generate-Checklists:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - uses: actions/checkout@v2
      with:
        repository: "OWASP/owasp-mstg.git"
        ref: "master"
        fetch-depth: 1
        path: owasp-mstg

    - name: Install pip Requirements
      run: pip3 install -r tools/requirements.txt

    - name: Convert MSTG Testing Chapters to HTML
      run: . tools/mstg_to_html.sh

    - name: Export YAML, enhance with MSTG and generate Excel
      run: cd tools && ./gen_all_excel.sh

    - name: Upload MASVS YAML
      uses: actions/upload-artifact@v2
      with:
        name: MASVS YAML Files
        path: tools/masvs_*.yaml

    - name: Upload Enhanced MASVS YAML
      uses: actions/upload-artifact@v2
      with:
        name: Enhanced MASVS YAML Files
        path: tools/masvs_full_*.yaml

    - name: Upload Checklists
      uses: actions/upload-artifact@v2
      with:
        name: Checklists
        path: tools/checklist_*.xlsx