name: Document Export

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - uses: actions/checkout@v2
      with:
        repository: "OWASP/owasp-mstg.git"
        ref: "master"
        fetch-depth: 1
        path: owasp-mstg

    - name: list from tools
      run: cd tools && ls ../owasp-mstg

    - name: list all
      run: ls -l

    - name: list mstg/Document
      run: ls -l owasp-mstg/Document

    - name: MSTG to HTML
      run: cd tools && . ./mstg_to_html.sh

    - name: Export YAML
      run: cd tools && python3 export.py -f yaml > masvs.yaml

    - name: Upload YAML export
      uses: actions/upload-artifact@v1
      with:
        name: masvs.yaml
        path: tools/masvs.yaml

    - name: Enhance YAML with MSTG Data
      run: cd tools && python3 parse_html.py

    - name: Upload Enhanced YAML export
      uses: actions/upload-artifact@v1
      with:
        name: masvs_full.yaml
        path: tools/masvs_full.yaml
    