name: Document Export

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - uses: actions/checkout@v2
      with:
        repository: "OWASP/owasp-mstg.git"
        ref: "master"
        fetch-depth: 1
        path: owasp-mstg

    - name: Install pip requirements
      run: pip3 install -r tools/requirements.txt

    - name: MSTG to HTML
      run: . tools/mstg_to_html.sh

    - name: Export YAML
      run: cd tools && ./gen_all_excel.sh

    - name: Upload YAML export
      uses: actions/upload-artifact@v2
      with:
        name: masvs.yaml
        path: tools/masvs_*.yaml

    - name: Upload Enhanced YAML export
      uses: actions/upload-artifact@v2
      with:
        name: enhanced_masvs
        path: tools/masvs_full_*.yaml

    - name: Upload Checklists
      uses: actions/upload-artifact@v2
      with:
        name: checklists
        path: tools/checklist_*.xlsx